package soroauth

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stellar/go-stellar-sdk/keypair"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// referenceSDK is the exact reference build the vectors must come from. A
// vector recorded by any other version is not evidence about this one, so the
// test refuses it rather than comparing against it.
const referenceSDK = "@stellar/stellar-sdk@17.1.0"

// vectorStep is one signing call to make, in order.
type vectorStep struct {
	SignerLabel string  `json:"signer_label"`
	ForAddress  *string `json:"for_address"`
}

// vectorDelegate describes the delegate tree a vector was built with. It is
// recorded for readability; the tree itself is already inside the unsigned
// entry.
type vectorDelegate struct {
	Label   string           `json:"label"`
	Address string           `json:"address"`
	Nested  []vectorDelegate `json:"nested"`
}

// vector is one golden case, as written by testdata/gen/gen.mjs.
type vector struct {
	Name              string           `json:"name"`
	SDK               string           `json:"sdk"`
	NetworkPassphrase string           `json:"network_passphrase"`
	ValidUntilLedger  uint32           `json:"valid_until_ledger"`
	UnsignedEntryXDR  string           `json:"unsigned_entry_xdr"`
	Delegates         []vectorDelegate `json:"delegates"`
	Steps             []vectorStep     `json:"steps"`
	PreimageXDR       string           `json:"preimage_xdr"`
	PayloadHex        string           `json:"payload_hex"`
	SignedEntryXDR    string           `json:"signed_entry_xdr"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()

	paths, err := filepath.Glob(filepath.Join("testdata", "vectors", "*.json"))
	if err != nil {
		t.Fatalf("globbing the vector directory: %v", err)
	}
	// Without this, deleting every vector would turn this file into a test
	// that passes by doing nothing.
	if len(paths) == 0 {
		t.Fatal("no golden vectors found in testdata/vectors; run `cd testdata/gen && npm ci && node gen.mjs`")
	}

	vectors := make([]vector, 0, len(paths))
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var v vector
		// Unknown fields are rejected so a schema change cannot be silently
		// half-ignored by this side.
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&v); err != nil {
			t.Fatalf("decoding %s: %v", path, err)
		}
		if v.Name == "" {
			t.Fatalf("%s has no name", path)
		}
		if v.SDK != referenceSDK {
			t.Fatalf("%s was generated by %q, want %q", path, v.SDK, referenceSDK)
		}
		vectors = append(vectors, v)
	}
	return vectors
}

// signerForLabel derives the vector's signing key from its label, the same way
// testdata/gen/gen.mjs does.
func signerForLabel(t *testing.T, label string) Signer {
	t.Helper()
	kp, err := keypair.FromRawSeed(sha256.Sum256([]byte(label)))
	if err != nil {
		t.Fatalf("deriving the keypair for %q: %v", label, err)
	}
	return NewEd25519Signer(kp)
}

// TestGoldenVectors is the correctness gate: for every recorded case, the
// preimage, the payload hash and the final signed entry must match the JS
// reference implementation byte for byte.
func TestGoldenVectors(t *testing.T) {
	for _, v := range loadVectors(t) {
		t.Run(v.Name, func(t *testing.T) {
			var entry xdr.SorobanAuthorizationEntry
			if err := xdr.SafeUnmarshalBase64(v.UnsignedEntryXDR, &entry); err != nil {
				t.Fatalf("decoding the unsigned entry: %v", err)
			}

			// 1. the preimage
			preimage, err := Preimage(entry, v.ValidUntilLedger, v.NetworkPassphrase)
			if err != nil {
				t.Fatalf("Preimage returned an unexpected error: %v", err)
			}
			gotPreimage, err := preimage.MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling the preimage: %v", err)
			}
			wantPreimage, err := base64.StdEncoding.DecodeString(v.PreimageXDR)
			if err != nil {
				t.Fatalf("decoding the expected preimage: %v", err)
			}
			if !equalBytes(gotPreimage, wantPreimage) {
				t.Errorf("preimage differs from the reference\n want %x\n  got %x", wantPreimage, gotPreimage)
			}

			// 2. the payload hash
			payload, err := Payload(preimage)
			if err != nil {
				t.Fatalf("Payload returned an unexpected error: %v", err)
			}
			if got := hex.EncodeToString(payload[:]); got != v.PayloadHex {
				t.Errorf("payload differs from the reference\n want %s\n  got %s", v.PayloadHex, got)
			}

			// 3. the signed entry, after replaying every signing step
			signed := entry
			for i, step := range v.Steps {
				var opts []AuthorizeOption
				if step.ForAddress != nil {
					opts = append(opts, ForAddress(*step.ForAddress))
				}
				signed, err = AuthorizeEntry(context.Background(), signed,
					signerForLabel(t, step.SignerLabel),
					v.ValidUntilLedger, v.NetworkPassphrase, opts...)
				if err != nil {
					t.Fatalf("step %d (%s) returned an unexpected error: %v", i, step.SignerLabel, err)
				}
			}

			gotSigned, err := signed.MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling the signed entry: %v", err)
			}
			wantSigned, err := base64.StdEncoding.DecodeString(v.SignedEntryXDR)
			if err != nil {
				t.Fatalf("decoding the expected signed entry: %v", err)
			}
			if !equalBytes(gotSigned, wantSigned) {
				t.Errorf("signed entry differs from the reference\n want %x\n  got %x", wantSigned, gotSigned)
			}
		})
	}
}

// TestGoldenVectorsCoverTheRequiredCases guards the set itself: a vector that
// is deleted, or never generated, must fail the build rather than quietly
// shrink the gate.
func TestGoldenVectorsCoverTheRequiredCases(t *testing.T) {
	required := []string{
		"legacy_single_testnet", // §5.9 case 1
		"legacy_single_public",  // §5.9 case 2
		"v2_single_testnet",     // §5.9 case 3
		"v2_sub_invocations",    // §5.9 case 4
		"v2_create_contract",    // §5.9 case 5
		"legacy_negative_nonce", // §5.9 case 9
	}

	present := map[string]bool{}
	for _, v := range loadVectors(t) {
		present[v.Name] = true
	}
	for _, name := range required {
		if !present[name] {
			t.Errorf("required golden vector %q is missing", name)
		}
	}
}

// TestGoldenPayloadsAreDistinct checks the separations §5.9 calls for, using
// the recorded payloads rather than recomputing them.
func TestGoldenPayloadsAreDistinct(t *testing.T) {
	payloads := map[string]string{}
	for _, v := range loadVectors(t) {
		payloads[v.Name] = v.PayloadHex
	}

	pairs := []struct {
		a, b   string
		reason string
	}{
		{
			a: "legacy_single_testnet", b: "legacy_single_public",
			reason: "a signature must not replay from testnet onto the public network",
		},
		{
			a: "legacy_single_testnet", b: "v2_single_testnet",
			reason: "V2 binds the address into the payload, so it must differ from legacy",
		},
		{
			a: "legacy_single_testnet", b: "legacy_negative_nonce",
			reason: "the nonce is what makes a signature single-use",
		},
	}

	for _, pair := range pairs {
		t.Run(pair.a+" vs "+pair.b, func(t *testing.T) {
			first, second := payloads[pair.a], payloads[pair.b]
			if first == "" || second == "" {
				t.Skipf("one of the vectors is missing (%q, %q)", pair.a, pair.b)
			}
			if first == second {
				t.Errorf("payloads collided (%s); %s", first, pair.reason)
			}
		})
	}
}

// equalBytes is bytes.Equal, named here so the golden assertions read as
// byte-for-byte comparisons.
func equalBytes(a, b []byte) bool { return bytes.Equal(a, b) }
